### ISSUE TITLE
PHP 5.4 compatibility

### ISSUE THREAD

**Issue by kasztnert** [microsec/passbyme-client-php#1]
If using on PHP 5.4, PassByME/TwoFactor/Send2FaRequest.php, line 34 throws a PHP fatal error, because empty() does not support return value of a function in PHP < 5.5. With a simple change it could be made compatible by replacing line 34 with the following:
$ca_cert = Config::get('ca_cert');
$caInfo = empty($ca_cert) ? $caPath : Config::get('ca_cert');

I have tried it and I could do an authentication, so it looks like this is the only compatibility issue.

**Comment by microsec** [comment]
Thank you for your remark. In version 1.0.1 we fixed the issue.

Happy authenticating!
